config/routes.rb
ProjectManager::Application.routes.draw do

  resources :projects do

    resources :backlogs 
   
    member do
     post 'backlogs/sort' => 'backlogs#sort', :as => 'sort_backlogs'
    end
  
    resources :sprints
  
  end #projects

end

app/models/backlog.rb
class Backlog < ActiveRecord::Base
  belongs_to :project

  # Ordenar os backlogs na base de dados, seguindo a ordem da lista backlog_ids
  def self.sort(backlog_ids)

    position = 0

    backlog_ids.each do |id|
      b = Backlog.find id
      b.update_attribute(:position, position)
      position = position + 1
    end

  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :backlogs, -> { order "position ASC" }, dependent: :destroy
  has_many :sprints

  def get_last_backlog_position
    backlogs.maximum(:position)
  end

end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController
  before_action :set_backlog, only: [:show, :edit, :update, :destroy]

  # GET /project/:project_id/backlogs
  # GET /project/:project_id/backlogs.json
  def index
    @project = Project.find params[:project_id].to_i
    @backlogs = @project.backlogs
  end

  # GET /project/:project_id/backlogs/1
  # GET /project/:project_id/backlogs/1.json
  def show
  end

  # GET /project/:project_id/backlogs/new
  def new
    @project = Project.find params[:project_id].to_i
    @backlog = @project.backlogs.build
  end

  # GET /project/:project_id/backlogs/1/edit
  def edit
    @project = Project.find params[:project_id].to_i
    @backlog = Backlog.find params[:id].to_i
  end

  # POST /project/:project_id/backlogs
  # POST /project/:project_id/backlogs.json
  def create

    @backlog = Backlog.new(backlog_params)
   
    # adiciona o backlog no final da lista
    p = Project.find params[:project_id]
    @backlog.position = (p.get_last_backlog_position + 1)

    respond_to do |format|
      if @backlog.save
        format.html { redirect_to project_backlogs_path(@backlog.project.id), notice: 'Backlog criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @backlog }
      else
        format.html { render action: 'new' }
        format.json { render json: @backlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project/:project_id/backlogs/1
  # PATCH/PUT /project/:project_id/backlogs/1.json
  def update
    respond_to do |format|
      if @backlog.update(backlog_params)
        format.html { redirect_to project_backlogs_path(@backlog.project.id), notice: 'Backlog atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @backlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project/:project_id/backlogs/1
  # DELETE /project/:project_id/backlogs/1.json
  def destroy
    project = @backlog.project
    @backlog.destroy
    respond_to do |format|
      format.html { redirect_to project_backlogs_path(project.id), :notice => "Backlog deletado com sucesso" }
      format.json { head :no_content }
    end
  end
 
  # POST /project/:project_id/backlog/sort
  def sort
    
    Backlog.sort(params[:backlogs])
    render :nothing => true, :status => 200

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backlog
      @backlog = Backlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backlog_params
      params.require(:backlog).permit(:title, :description, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @backlogs = @project.backlogs
    @sprints = @project.sprints
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to action: 'index' }
        format.json { render action: 'index', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to action: 'index' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :set_sprint, only: [:show, :edit, :update, :destroy]

  # GET /project/:project_id/sprints
  # GET /project/:project_id/sprints.json
  def index
    @project = Project.find params[:project_id].to_i
    @sprints = @project.sprints
  end

  # GET /project/:project_id/sprints/1
  # GET /project/:project_id/sprints/1.json
  def show
  end

  # GET /sprints/new
  def new
    #@sprint = Sprint.new
    @project = Project.find params[:project_id].to_i
    @sprint = @project.sprints.build
  end

  # GET /project/:project_id/sprints/1/edit
  def edit
    @project = Project.find params[:project_id].to_i
    @sprint = Sprint.find params[:id].to_i
  end

  # POST /sprints
  # POST /sprints.json
  def create
    
    @sprint = Sprint.new(sprint_params)

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to @sprint.project, notice: 'Sprint criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @sprint }
      else
        format.html { render action: 'new' }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprints/1
  # PATCH/PUT /sprints/1.json
  def update
    respond_to do |format|
      if @sprint.update(sprint_params)
        format.html { redirect_to project_sprints_path(@sprint.project.id), notice: 'Sprint atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprints/1
  # DELETE /sprints/1.json
  def destroy
    project = @sprint.project
    @sprint.destroy
    respond_to do |format|
      format.html { redirect_to project_sprints_path(project.id), :notice => "Sprint deletado com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprint
      @sprint = Sprint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sprint_params
      params.require(:sprint).permit(:title, :description, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backlogs_helper.rb
module BacklogsHelper
end

app/helpers/date_helper.rb
module DateHelper

  def to_br_date(date)
    date.strftime("%d/%m/%Y %H:%M:%S")
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/backlogs/_form.html.erb
<%= form_for [@project, @backlog] do |f| %> 
  <div class="control-group">
    <%= f.label "Titulo", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Descrição", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.hidden_field :project_id %>
    <%= f.submit "Criar backlog", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/backlogs/edit.html.erb
<%- model_class = Backlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/backlogs/index.html.erb
<%- model_class = Backlog -%>
<% @active = 'backlogs' %>

<div class="page-header">
  <h1><%= @project.name %></h1>
</div>

<%= render :partial => 'projects/navigation' %>

<table id="backlogs" class="table table-striped">
  <thead>
    <tr>
      <th>Backlog</th>
      <th>Data de criação</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @backlogs.each do |backlog| %>
      <tr id="<%= backlog.id %>">
        <td><%= backlog.title %></td>
        <td><%= to_br_date(backlog.created_at) %></td>
        <td>
          <%= link_to_modal "Editar", edit_project_backlog_path(backlog.project_id, backlog.id), :class => "btn btn-primary" %>
          <%= link_to t('.destroy', :default => "Deletar"),
                      project_backlog_path(backlog.project.id, backlog.id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => 'Você tem certeza que deseja deletar este backlog?') },
                      :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to_modal "Adicionar backlog", new_project_backlog_path(@project.id), :class => "btn btn-primary"%>

<%= javascript_tag do %>

  $(document).ready(function() {
    $("#backlogs").tableDnD({
      onDrop: function(table, row) {
        $.ajax({
          type: "POST",
          url: "<%= sort_backlogs_project_path @project %>",
          processData: false,
          data: $.tableDnD.serialize(),
          success: function(msg) {
          }
        });
      }
    });
  });

<% end %>

app/views/backlogs/new.html.erb
<%- model_class = Backlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/backlogs/show.html.erb
<%- model_class = Backlog -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @backlog.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @backlog.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @backlog.project_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              backlogs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_backlog_path(@backlog), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              backlog_path(@backlog),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Team Metrics" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Team Metrics</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
<!--
      <footer>
        <p>&copy; Company 2013</p>
      </footer>
-->
    </div> <!-- /container -->

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Nome", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Descrição", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Salvar", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => "Cancelar"),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/_navigation.html.erb
<ul class="nav nav-tabs">
  <li class="<%= 'active' if current_page?(project_backlogs_path) %>"><%= link_to "Backlogs", project_backlogs_path(@project) %></li>
  <li class="<%= 'active' if current_page?(project_sprints_path) %>"><%= link_to "Sprints", project_sprints_path(@project) %></li>
  <li><a href="#tab_members" data-toggle="tab">Membros do time</a></li>
</ul>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Editar projeto" %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>Projetos</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome do projeto</th>
      <th>Data de criação</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_backlogs_path(project) %></td>
        <td><%= to_br_date(project.created_at) %></td>

        <td>
          <%= link_to t('.edit', :default => "Editar"),
                      edit_project_path(project),
                      :method => :get,
                      :class => 'btn btn-primary' %>          
          <%= link_to t('.destroy', :default => "Deletar"),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => 'Você tem certeza que deseja deletar este projeto?') },
                      :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => "Criar novo projeto"),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>Criar novo projeto</h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%= @project.name %></h1>
</div>

<div class="tabbable">
  
  <%= render :partial => "projects/navigation" %>

  <!-- tabs -->
  <div class="tab-content">
    
    <!-- backlog -->
    <div class="tab-pane active" id="tab_backlog">
      <%= render template: 'backlogs/index' %>
      <%= link_to_modal "Adicionar backlog", new_project_backlog_path(@project.id), :class => "btn btn-primary"%>
    </div>
    
    <!-- sprints -->
    <div class="tab-pane" id="tab_sprints">
      <%= render template: 'sprints/index' %>
      <%= link_to_modal "Adicionar sprint", new_project_sprint_path(@project.id), :class => "btn btn-primary"%>
    </div>

    <!-- members -->
    <div class="tab-pane" id="tab_members">
      <p>Membros do time</p>
    </div>
  
  </div>

</div>

<!-- modal create backlog -->
<div id="create-backlog" style="display: none;">
  <%= render template: 'backlogs/new' %>
</div>

<%= javascript_tag do %>

  $(document).ready(function() {
    $("#backlogs").tableDnD({
      onDrop: function(table, row) {
        $.ajax({
          type: "POST",
          url: "<%= sort_backlogs_project_path @project %>",
          processData: false,
          data: $.tableDnD.serialize(),
          success: function(msg) {
          }
        });
      }
    });
  });

<% end %>

app/views/sprints/_form.html.erb
<%= form_for [@project, @sprint] do |f| %>
  <div class="control-group">
    <%= f.label "Nome", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>  
  </div>
  <div class="control-group">
    <%= f.label "Descricao", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.hidden_field :project_id %>
    <%= f.submit "Salvar", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/sprints/edit.html.erb
<%- model_class = Sprint -%>
<div class="page-header">
  <h1>Editing sprint</h1>
</div>
<%= render 'form' %>

app/views/sprints/index.html.erb
<%- model_class = Sprint -%>

<div class="page-header">
  <h1><%= @project.name %></h1>
</div>

<%= render :partial => 'projects/navigation' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Sprint</th>
      <th>Data de criação</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @sprints.each do |sprint| %>
      <tr>
        <td><%= sprint.title %></td>
        <td><%= to_br_date(sprint.created_at) %></td>
        <td>
          <%= link_to_modal "Editar", edit_project_sprint_path(sprint.project_id, sprint.id), :class => "btn btn-primary" %>
          <%= link_to t('.destroy', :default => "Deletar"),
                      project_sprint_path(sprint.project.id, sprint.id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => 'Você tem certeza que deseja deletar este sprint?') },
                      :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sprints/new.html.erb
<%- model_class = Sprint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sprint.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sprint.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @sprint.project %>
</p>

<%= link_to 'Edit', edit_sprint_path(@sprint) %> |
<%= link_to 'Back', sprints_path %>